version: "3.3"
services:
    coffeebuddydb:
      image: postgres
      command: |
        -c ssl=on
        -c ssl_ca_file=/certs/ca/root.crt
        -c ssl_cert_file=/certs/server_coffeebuddydb/server.crt
        -c ssl_key_file=/certs/server_coffeebuddydb/server.key
      entrypoint: entrypoint.sh
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: coffeebuddy
        POSTGRES_PASSWORD: example
      volumes:
        - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
        - ./certs:/_certs
        - ./users.txt:/users.txt
