version: "3.3"

services:
  nginx:
    image: tobi312/rpi-nginx:latest
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./ssl:/etc/ssl/
    ports:
      - 443:443
    network_mode: host
