name: lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Format with black
      run: |
        pip install black
        black --check .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --extend-ignore=W503
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint coffeebuddy
