name: lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install --user pdm
          pdm sync -G dev
      - name: Format
        run: |
          pdm run ruff format --check .
      - name: Lint
        run: |
          pdm run ruff check .
      - name: Djlint
        run: |
          pdm run djlint coffeebuddy
